name: Release Build and push to Azure

on:
  push:
    branches:
      - main

jobs:
  Build-and-push-to-Azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        run: az acr login --name wildoasis --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: wildoasis.azurecr.io/wildOasis:latest

      - name: Bring down existing containers
        run: docker-compose down

      - name: Bring up new containers
        run: docker-compose up

      - name: Run container
        run: docker run -d -p 8080:8080 wildoasis.azurecr.io/wildoasis:latest